# Generated by Django 4.2.3 on 2023-07-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ancestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="кличка")),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
            ],
            options={
                "verbose_name": "предок",
                "verbose_name_plural": "предки",
            },
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="наименование")),
                ("description", models.TextField(verbose_name="описание")),
            ],
            options={
                "verbose_name": "порода",
                "verbose_name_plural": "породы",
            },
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="кличка")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="фотография"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dogs.breed"
                    ),
                ),
            ],
            options={
                "verbose_name": "собака",
                "verbose_name_plural": "собаки",
            },
        ),
    ]
