# Generated by Django 4.2.3 on 2023-07-23 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ancestor",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dogs.breed"
            ),
        ),
        migrations.AddField(
            model_name="ancestor",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dogs.dog"
            ),
        ),
    ]
