# Generated by Django 4.2.3 on 2023-07-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dogs",
                to="dogs.breed",
            ),
        ),
    ]
