# Generated by Django 4.2.3 on 2023-07-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0003_alter_dog_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="public",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="публичная"
            ),
        ),
    ]
