# Generated by Django 4.2.3 on 2023-07-25 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0004_dog_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dog",
            old_name="public",
            new_name="published",
        ),
    ]
