# Generated by Django 4.2.3 on 2023-07-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0005_rename_public_dog_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
