# Generated by Django 4.2.3 on 2023-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="видео"
            ),
        ),
    ]
