# Generated by Django 4.2.3 on 2023-07-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_alter_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.course",
            ),
            preserve_default=False,
        ),
    ]
