# Generated by Django 4.2.3 on 2023-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0004_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="дата оплаты"),
        ),
    ]
