# Generated by Django 4.2.3 on 2023-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0012_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="amount",
            field=models.PositiveIntegerField(default=0, verbose_name="сумма"),
            preserve_default=False,
        ),
    ]
