# Generated by Django 4.2.3 on 2023-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0013_intent_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intent",
            options={
                "verbose_name": "client secret",
                "verbose_name_plural": "client secrets",
            },
        ),
        migrations.AddField(
            model_name="intent",
            name="secret",
            field=models.CharField(
                default=None, max_length=100, verbose_name="scient secret"
            ),
            preserve_default=False,
        ),
    ]
