# Generated by Django 4.2.3 on 2023-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0014_alter_intent_options_intent_secret"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intent",
            options={"verbose_name": "статус", "verbose_name_plural": "статусы"},
        ),
        migrations.AddField(
            model_name="intent",
            name="status",
            field=models.CharField(default=None, max_length=50, verbose_name="статус"),
            preserve_default=False,
        ),
    ]
